base-host: localhost
redis-host: 172.17.213.249
mysql-connection-host: ${base-host}
mysql-connection-port: 3306
mysql-db-name: oj
mysql-username: root
mysql-password: 123456

redis-connection-host: ${redis-host}
redis-connection-port: 6379

#---------------------------------------------------------------

testCaseSaveLocation: W:\my\OnlineJudgeDeploy\data\backend\test_case\

judge:
  host: ${base-host}
  port: 9000
#---------------------------------------------------------------

server:
  port: 9991
# 自定义额外的端口
#additional-ports: 9999

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql-connection-host}:${mysql-connection-port}/${mysql-db-name}?serverTimezone=GMT%2B8&useUnicode=true&amp&characterEncoding=utf-8
    username: ${mysql-username}
    password: ${mysql-password}
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: ${redis-connection-host}
    port: ${redis-connection-port}
    password: 123321
    database: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB #指定上传文件允许的最大大小
      max-request-size: 100MB #指定multipart/form-data请求允许的最大大小

mybatis-plus:
  type-aliases-package: one.sunny.ttoj.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted # ????????
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl